spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lianxi_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 439917

logging:
  level:
    root: INFO
    com.example.usergenerator: INFO
    com.baomidou.mybatisplus: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
